# Metadata for the site header and footer
title: My website
description: A website made with GitHub Pages

# Set the production website URL when previewing
baseurl: "/write-the-docs"

# Markdown parser and theme settings
markdown: kramdown
theme: minima

# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Quantum espresso
author: Mohan Giri
logo: logo.jpg

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "./logo.jpg"
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-MBS9YS5YW0
